#!/bin/bash

# execute "$@" for all panes of the active session
# does not need to be attached

# ensure there is a session
tmux has-session 2> /dev/null
if [ "$?" -ne 0 ]; then
  echo "missing session"
  exit "$?"
fi

NUMBER_OF_PANES="$(tmux list-panes | wc -l | tr -d ' ')"

for i in $(seq 1 ${NUMBER_OF_PANES}); do
  tmux select-pane -t ":.${i}"
  tmux send-keys "${@}" Enter
done

